library identifier: 'jenkins-pipeline-demo-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/mohammed-gaber-ramadan/jenkins-pipeline-demo-library.git'],credentialsId: 'mohammed-gaber-ramadan')

pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                auditTools()
            }
        }
    }
}
